### ISSUE TITLE
The website is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [HICAI-ZJU/SciKnowEval#2]
Check http://scimind.ai/sciknoweval but found:
<img width="760" alt="image" src="https://github.com/user-attachments/assets/0ccdb0bc-ade0-4698-b4fd-1fdea8f71d99">

**Comment by dingkeyan93** [comment]
The website has been restored

**Comment by dingkeyan93** [comment]
The website has been restored

**Comment by wwbmmm** [comment]
The website is inaccessible now:

![Image](https://github.com/user-attachments/assets/960f7d68-3896-4eb6-acd7-1638b97d7c38)
